---
- name: Install python3-debian
  apt:
    name: python3-debian
    state: present

- name: Get system architecture
  command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Add Docker APT repository
  deb822_repository:
    name: docker
    types: deb
    architectures: "{{ dpkg_architecture.stdout }}"
    uris: https://download.docker.com/linux/{{ ansible_lsb.id | lower }}
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg
  register: add_docker_repo

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: "{{ add_docker_repo.changed }}"
